### ISSUE TITLE
Integers decode incorrectly when the last encoded byte is a whitespace character.

### ISSUE THREAD

**Issue by elewando** [flix-tech/avro-serde-php#31]
```
<?php

require_once('vendor/autoload.php');

use GuzzleHttp\Client;

use FlixTech\AvroSerializer\Objects\RecordSerializer;
use FlixTech\SchemaRegistryApi\Registry\CachedRegistry;
use FlixTech\SchemaRegistryApi\Registry\PromisingRegistry;
use FlixTech\SchemaRegistryApi\Registry\Cache\AvroObjectCacheAdapter;

$registry = new CachedRegistry(
	new PromisingRegistry(
		new Client(['base_uri' => 'schema-registry:8081'])
	),
	new AvroObjectCacheAdapter()
);

$serializer = new RecordSerializer(
	$registry,
	[
		RecordSerializer::OPTION_REGISTER_MISSING_SCHEMAS => true,
		RecordSerializer::OPTION_REGISTER_MISSING_SUBJECTS => true, 
	]
);

$schema = AvroSchema::parse('{"name":"Key","type":"record","fields":[{"name":"project_date_id","type":"int"}]}');
$record = ['project_date_id' => 13829974];

$encoded = $serializer->encodeRecord('bytes-test', $schema, $record);
echo implode(' ', array_map('ord', str_split($encoded))) . PHP_EOL;
echo $serializer->decodeMessage($encoded)['project_date_id'] . PHP_EOL;
```

Produces this output:

```
0 0 0 0 21 172 157 152 13
198486
```

The fifth byte will vary with your registry, but the result is that the original id, 13829974, becomes 198486 after encoding/decoding. I've tracked it down to this line:

https://github.com/flix-tech/avro-serde-php/blob/c488c0624ed357c6daedfdf9bfa3402b9e40aca4/src/Protocol.php#L61

Where this happens:

https://www.php.net/manual/en/function.unpack.php

> The "A" code now strips all trailing ASCII whitespace (spaces, tabs, newlines, carriage returns, and NULL bytes).

So the uppercase _A_ in the format string is dropping the last byte (13) because it thinks it is whitespace. A lowercase _a_ seems to work correctly.

**Comment by sergeygardner** [comment]
Hi!

Could you tell me, when this bug will be fixed?

Thanks!

**Comment by tPl0ch** [comment]
@sergeygardner @elewando The fix has been released as https://github.com/flix-tech/avro-serde-php/releases/tag/1.6.1

**Comment by stunner2002** [comment]
This issue is not fixed. @elewando pointed to the `decode` method but the fix has been made for `encode` only.
